[2023-10-22T20:41:40.144+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_score.train_test_split manual__2023-10-22T16:41:33.660598+00:00 [queued]>
[2023-10-22T20:41:40.148+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_score.train_test_split manual__2023-10-22T16:41:33.660598+00:00 [queued]>
[2023-10-22T20:41:40.149+0400] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-22T20:41:40.162+0400] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_test_split> on 2023-10-22 16:41:33.660598+00:00
[2023-10-22T20:41:40.164+0400] {standard_task_runner.py:57} INFO - Started process 8191 to run task
[2023-10-22T20:41:40.167+0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'iris_score', 'train_test_split', 'manual__2023-10-22T16:41:33.660598+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/iris_score.py', '--cfg-path', '/tmp/tmp68bzejvm']
[2023-10-22T20:41:40.168+0400] {standard_task_runner.py:85} INFO - Job 14: Subtask train_test_split
[2023-10-22T20:41:40.242+0400] {task_command.py:416} INFO - Running <TaskInstance: iris_score.train_test_split manual__2023-10-22T16:41:33.660598+00:00 [running]> on host primary
[2023-10-22T20:41:40.271+0400] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='iris_score' AIRFLOW_CTX_TASK_ID='train_test_split' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T16:41:33.660598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T16:41:33.660598+00:00'
[2023-10-22T20:41:40.271+0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-22T20:41:40.272+0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/pyretttt/repos/mlops3/scripts/train_test_split.py']
[2023-10-22T20:41:40.277+0400] {subprocess.py:86} INFO - Output:
[2023-10-22T20:41:40.885+0400] {subprocess.py:93} INFO - /home/pyretttt/repos/mlops3/env/lib/python3.10/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-10-22T20:41:40.885+0400] {subprocess.py:93} INFO - 
[2023-10-22T20:41:40.886+0400] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-10-22T20:41:40.886+0400] {subprocess.py:93} INFO -   warnings.warn(
[2023-10-22T20:41:40.889+0400] {subprocess.py:93} INFO - /home/pyretttt/repos/mlops3/env/lib/python3.10/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
[2023-10-22T20:41:40.890+0400] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-10-22T20:41:40.890+0400] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-10-22T20:41:40.901+0400] {subprocess.py:93} INFO - 2023/10/22 20:41:40 INFO mlflow.tracking.fluent: Experiment with name 'train_test_split' does not exist. Creating a new experiment.
[2023-10-22T20:41:41.107+0400] {subprocess.py:97} INFO - Command exited with return code 0
[2023-10-22T20:41:41.125+0400] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=iris_score, task_id=train_test_split, execution_date=20231022T164133, start_date=20231022T164140, end_date=20231022T164141
[2023-10-22T20:41:41.159+0400] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T20:41:41.215+0400] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
